theme: jekyll-theme-midnight
title: Tugamer89
description: "Student passionate about Computer Science, Programming, and Cybersecurity"
webmaster_verifications:
  google: yR04oI5NTEJeO6htVqmUek7P6GezU-Mn-zRJegqdwL4
  yandex: fe2e9e5b84cda188