name: Update fork star

on:
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: "55 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: This repo has x stars y forks
        uses: ouuan/This-repo-has-x-stars-y-forks-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: "Tugamer89's profile with <starCount> stars ⭐ and <forkCount> forks 🎉"
